import { z } from 'zod'
import { zId, zPage, zPageSize, zMaybeString, zDateLike } from '../../schema/common'

export const assetsListQuerySchema = z.object({
  page: zPage.optional(),
  pageSize: zPageSize.optional(),
  q: zMaybeString,
  status: zMaybeString,
  category: zMaybeString,
  assignedToId: zId.optional(),
})

export const assetIdParamsSchema = z.object({
  id: zId,
})

export const assetsCreateBodySchema = z.object({
  assetId: z.string().min(1).optional(),
  name: z.string().optional(),
  displayName: z.string().optional(),
  description: z.string().optional(),
  assetType: z.string().min(1),
  assetTypeId: z.string().optional(),
  category: z.string().min(1),
  status: z.string().min(1),
  subcategory: z.string().optional(),
  ciType: z.string().optional(),
  impact: z.string().optional(),
  usageType: z.string().optional(),
  serial: z.string().optional(),
  assetTag: z.string().optional(),
  barcode: z.string().optional(),
  domain: z.string().optional(),
  region: z.string().optional(),
  availabilityZone: z.string().optional(),
  assignedToId: zId.optional().nullable(),
  assignedUserEmail: z.string().email().optional().nullable(),
  department: z.string().optional(),
  location: z.string().optional(),
  site: z.string().optional(),
  managedByGroup: z.string().optional(),
  company: z.string().optional(),
  usedBy: z.string().optional(),
  managedBy: z.string().optional(),
  assignedOn: zDateLike.optional(),
  costCentre: z.string().optional(),
  manager: z.string().optional(),
  assetOwner: z.string().optional(),
  manufacturer: z.string().optional(),
  model: z.string().optional(),
  hardwareType: z.string().optional(),
  physicalSubtype: z.string().optional(),
  virtualSubtype: z.string().optional(),
  product: z.string().optional(),
  cpu: z.string().optional(),
  ram: z.string().optional(),
  storage: z.string().optional(),
  cpuSpeed: z.string().optional(),
  cpuCoreCount: z.string().optional(),
  osServicePack: z.string().optional(),
  macAddress: z.string().optional(),
  uuid: z.string().optional(),
  hostname: z.string().optional(),
  lastLoginBy: z.string().optional(),
  ipAddress: z.string().optional(),
  biosVersion: z.string().optional(),
  firmware: z.string().optional(),
  os: z.string().optional(),
  osVersion: z.string().optional(),
  licenseKey: z.string().optional(),
  installedSoftware: z.array(z.string()).optional(),
  antivirus: z.string().optional(),
  patchStatus: z.string().optional(),
  encryption: z.string().optional(),
  vendor: z.string().optional(),
  acquisitionType: z.string().optional(),
  rentalProvider: z.string().optional(),
  rentalStartDate: zDateLike.optional(),
  rentalEndDate: zDateLike.optional(),
  rentalMonthlyCost: z.number().optional(),
  rentalTotalCost: z.number().optional(),
  maintenanceIncluded: z.boolean().optional(),
  contractNumber: z.string().optional(),
  returnCondition: z.string().optional(),
  purchaseDate: zDateLike.optional(),
  acquisitionDate: zDateLike.optional(),
  supplier: z.string().optional(),
  poNumber: z.string().optional(),
  invoiceNumber: z.string().optional(),
  purchaseCost: z.number().optional(),
  cost: z.number().optional(),
  salvageValue: z.number().optional(),
  depreciationType: z.string().optional(),
  warrantyYears: z.number().optional(),
  warrantyMonths: z.number().optional(),
  warrantyStart: zDateLike.optional(),
  warrantyUntil: zDateLike.optional(),
  warrantyExpiryAt: zDateLike.optional(),
  amcSupport: z.string().optional(),
  depreciationEnd: zDateLike.optional(),
  lifecycleStage: z.string().optional(),
  condition: z.string().optional(),
  deploymentDate: zDateLike.optional(),
  lastAuditDate: zDateLike.optional(),
  endOfLife: zDateLike.optional(),
  disposalDate: zDateLike.optional(),
  disposalMethod: z.string().optional(),
  securityClassification: z.string().optional(),
  dataSensitivity: z.string().optional(),
  mdmEnrolled: z.boolean().optional(),
  complianceStatus: z.string().optional(),
  riskLevel: z.string().optional(),
  lastSecurityScan: zDateLike.optional(),
  itemId: z.string().optional(),
  itemName: z.string().optional(),
  publicAddress: z.string().optional(),
  instanceState: z.string().optional(),
  instanceType: z.string().optional(),
  provider: z.string().optional(),
  creationTimestamp: zDateLike.optional(),
  parentAssetId: zId.optional().nullable(),
  notes: z.string().optional(),
  customFields: z.record(z.any()).optional(),
  linkedTicketIds: z.array(z.string()).optional(),
  changeIds: z.array(z.number()).optional(),
  problemIds: z.array(z.number()).optional(),
  serviceIds: z.array(z.number()).optional(),
})

export const assetsUpdateBodySchema = assetsCreateBodySchema.partial()
