import { z } from 'zod'
import { zId, zPage, zPageSize, zMaybeString, zDateLike } from '../../schema/common'

export const assetsListQuerySchema = z.object({
  page: zPage.optional(),
  pageSize: zPageSize.optional(),
  q: zMaybeString,
  status: zMaybeString,
  category: zMaybeString,
  assignedToId: zId.optional(),
})

export const assetIdParamsSchema = z.object({
  id: zId,
})

export const assetsCreateBodySchema = z.object({
  assetId: z.string().min(1),
  name: z.string().min(1),
  assetType: z.string().min(1),
  category: z.string().min(1),
  status: z.string().min(1),
  subcategory: z.string().optional(),
  ciType: z.string().optional(),
  serial: z.string().optional(),
  assetTag: z.string().optional(),
  barcode: z.string().optional(),
  assignedToId: zId.optional().nullable(),
  assignedUserEmail: z.string().email().optional().nullable(),
  department: z.string().optional(),
  location: z.string().optional(),
  site: z.string().optional(),
  costCentre: z.string().optional(),
  manager: z.string().optional(),
  assetOwner: z.string().optional(),
  manufacturer: z.string().optional(),
  model: z.string().optional(),
  cpu: z.string().optional(),
  ram: z.string().optional(),
  storage: z.string().optional(),
  macAddress: z.string().optional(),
  ipAddress: z.string().optional(),
  biosVersion: z.string().optional(),
  firmware: z.string().optional(),
  os: z.string().optional(),
  osVersion: z.string().optional(),
  licenseKey: z.string().optional(),
  installedSoftware: z.array(z.string()).optional(),
  antivirus: z.string().optional(),
  patchStatus: z.string().optional(),
  encryption: z.string().optional(),
  purchaseDate: zDateLike.optional(),
  supplier: z.string().optional(),
  poNumber: z.string().optional(),
  invoiceNumber: z.string().optional(),
  purchaseCost: z.number().optional(),
  warrantyStart: zDateLike.optional(),
  warrantyUntil: zDateLike.optional(),
  amcSupport: z.string().optional(),
  depreciationEnd: zDateLike.optional(),
  lifecycleStage: z.string().optional(),
  condition: z.string().optional(),
  deploymentDate: zDateLike.optional(),
  lastAuditDate: zDateLike.optional(),
  endOfLife: zDateLike.optional(),
  disposalDate: zDateLike.optional(),
  disposalMethod: z.string().optional(),
  securityClassification: z.string().optional(),
  dataSensitivity: z.string().optional(),
  mdmEnrolled: z.boolean().optional(),
  complianceStatus: z.string().optional(),
  riskLevel: z.string().optional(),
  lastSecurityScan: zDateLike.optional(),
  parentAssetId: zId.optional().nullable(),
  notes: z.string().optional(),
  linkedTicketIds: z.array(z.string()).optional(),
  changeIds: z.array(z.number()).optional(),
  problemIds: z.array(z.number()).optional(),
  serviceIds: z.array(z.number()).optional(),
})

export const assetsUpdateBodySchema = assetsCreateBodySchema.partial()
